
--------------------->INSERT PROCEDURE
CREATE OR ALTER PROCEDURE [dbo].[PR_USER_INSERT]
@USERNAME NVARCHAR(100),
@PASSWORD NVARCHAR(100),
@EMAIL NVARCHAR(100),
@MOBILE NVARCHAR(100),
@ISACTIVE BIT,
@MODIFIED DATETIME

AS
BEGIN
	INSERT INTO [dbo].[USER]
	VALUES(@USERNAME, @PASSWORD ,@EMAIL, @MOBILE, @ISACTIVE,getdate(), @MODIFIED)
END


------------------SELECTALL PROCEDURE----------->
CREATE OR ALTER PROCEDURE [dbo].[PR_USER_SELECTALL]
AS
BEGIN
	SELECT * FROM [dbo].[User]
END

